{"uuid":"d882bd3f-a010-4385-9f75-da1cdae4e353","historyId":"f58a9edbaee2ec592557137e179de372","fullName":"testcases.TestLogin.testLoginWithValidCredentials","labels":[{"name":"package","value":"testcases.TestLogin"},{"name":"testClass","value":"testcases.TestLogin"},{"name":"testMethod","value":"testLoginWithValidCredentials"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"WebAutomation-Rokomari"},{"name":"subSuite","value":"testcases.TestLogin"},{"name":"host","value":"DESKTOP-RQ27ESO"},{"name":"thread","value":"5720@DESKTOP-RQ27ESO.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"feature","value":"Essential features"},{"name":"story","value":"Authentication"},{"name":"epic","value":"Web interface"}],"links":[],"name":" User log in with valid Credentials","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"chromedriver at location path_to_chromedriver.exe, does not exist\nFor documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/\nBuild info: version: '4.18.1', revision: 'b1d3319b48'\nSystem info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.21'\nDriver info: driver.version: ChromeDriver","trace":"org.openqa.selenium.remote.NoSuchDriverException: chromedriver at location path_to_chromedriver.exe, does not exist\nFor documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/\nBuild info: version: '4.18.1', revision: 'b1d3319b48'\nSystem info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.21'\nDriver info: driver.version: ChromeDriver\r\n\tat org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:76)\r\n\tat org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:33)\r\n\tat org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:99)\r\n\tat org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:89)\r\n\tat org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)\r\n\tat org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:73)\r\n\tat utilities.BrowserSetup.getBrowser(BrowserSetup.java:38)\r\n\tat utilities.BrowserSetup.startBrowser(BrowserSetup.java:65)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1228)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1134)\r\n\tat org.testng.TestNG.run(TestNG.java:1101)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":" Test Add using allure: User log in with valid Credentials","steps":[],"attachments":[],"parameters":[],"start":1717909324297,"stop":1717909324302}